name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ucsc-vama/compare-gen
        ref: master
        token: ${{ secrets.CLASSIC_ACTION_TOK }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: fetch submodule
      run: git submodule update --init --recursive
      with:
        repository: ucsc-vama/compare-gen
        ref: master
        token: ${{ secrets.CLASSIC_ACTION_TOK }}
    - name: update remote submodule
      run: git submodule update --recursive --remote
      with:
        repository: ucsc-vama/compare-gen
        ref: master
        token: ${{ secrets.CLASSIC_ACTION_TOK }}
    - name: run test
      run: |
        python3 BruteTest.py -t uint -s 3