name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cd firrtl-operations
        python3 test_uint.py
        cd ..
    - name: fetch submodule
      run: git submodule update --init --remote
    - name: update remote submodule
      run: git submodule update --recursive --remote
    - name: run test
      run: |
        python3 BruteTest.py -t uint -s 3