name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: fetch submodule
      run: git submodule update --init --remote
    - name: update remote submodule
      run: git submodule update --recursive --remote
    - name: see folder
      working-directory: ./firrtl-operations
      run: |
        ls
    - name: run unit test
      working-directory: ./firrtl-operations
      run: |
        python3 test_uint.py